export const IS_MESSAGE_LOADING  = 'IS_MESSAGE_LOADING';
export const LOADING_DONE  = 'LOADING_DONE  ';
export const MESSAGE_ERROR = 'MESSAGE_ERROR';
export const MESSAGE_SEND_SUCCESS  = 'MESSAGE_SEND_SUCCESS';
